### ISSUE TITLE
Investigate/adjust use of poolee retries

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-db-mysql#9] opened 2015-02-06 04:41 UTC
During load tests, there was at least one episode where a series of timeouts happened on the fxa-auth servers, followed by a series of 500 errors. I'm not sure exactly what the root cause was but roughly something caused some PUT /sessionToken/<hash> to block, and then the auth-server apparently retried these PUT requests. The retry of the PUT's resulted in 409 Conflict due to duplicate key when the first PUT was unblocked. 

STR:
1 - Drive traffic into a test environment
2 - In mysql: `lock tables sessionTokens write; select sleep(11); unlock tables;`

Anyways, we should look into whether we should be disabling retires in `poolee`, or using a retryFilter that allows known idempotent queries to retry but disallows others.

**Comment by chilts** [comment] 2015-02-08 22:00
When looking at this with @jrgm, I think the sequence went something like this:

* auth-server sends request to db-server
* db-server sends request to MySql
* this request somehow gets stalled in MySql, but eventually succeeds after perhaps 6 or 7 seconds (as John says above, we couldn't figure out what the root cause was here)
* meanwhile, the poolee set in the auth-server has timed out after 5 seconds - https://github.com/mozilla/fxa-auth-server/blob/master/pool.js#L27
* since poolee has been told to retry, it sends the request again to the db-server
* meanwhile in the db-server, the request comes back as successful but the response essentially goes nowhere since the auth-server has timed out
* the db-server receives the 2nd request (the retry) from the auth-server and sends it to MySql again
* this time since the original request actually worked, it'll fail on a duplicate key error, which materialises as the 409 Conflict

We thought about a few other options such as retries only happen with GETs and HEADs, but not with POSTs, PUTs and DELs.

**Comment by rfk** [comment] 2015-02-08 22:41
I'll put in a vote for just disabling retries entirely in the interests of simplicity.  We already have some amount of retry login within the auth-db-server itself, it's not clear what value we'd get from another layer.

**Comment by rfk** [comment] 2015-02-08 22:42
(Alternately, maybe it's worth retrying for HTTP-level errors like e.g. a `502` but not for timeouts...simplicity still sounds like the best approach though)

**Comment by jrgm** [comment] 2015-02-24 23:57
So, removing the retry is the way to go.

**Comment by chilts** [comment] 2015-05-05 22:47
Closing since fixed in https://github.com/mozilla/fxa-auth-server/pull/922.

**Closed by chilts** 2015-05-05 22:47 UTC
Labels: backlog, waffle:in progress
