### ISSUE TITLE
Intermittent failure in token-pruning test

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#428] opened 2018-11-01 13:33 UTC
Saw this one time in Travis, hasn't happened since:

```
  389 passing (18s)
  1 failing

  1) prune tokens
       prune tokens:
     Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD
   Incorrect string value: '\xF1\xA6\xBF\xB5\xEF\xBF...' for column 'inNormalizedEmail' at row 1
      at Query.Sequence._packetToError (node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:103:28)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:601:20)
      --------------------
      at Protocol._enqueue (node_modules/mysql/lib/protocol/Protocol.js:145:48)
      at PoolConnection.query (node_modules/mysql/lib/Connection.js:208:25)
      at query (lib/db/mysql.js:210:1400)
      at /home/travis/build/mozilla/fxa-auth-db-mysql/lib/db/mysql.js:205:246
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by shane-tomlinson** [comment] 2018-11-05 17:16
Closing until we can reproduce.

**Comment by rfk** [comment] 2018-11-22 03:49
I think I found the cause of this, re-opening so I can attach a PR.

**Closed** 2018-11-22 15:01 UTC
Labels: waffle:review
