### ISSUE TITLE
Verification Reminders hit OperationalError on stable.dev.lcip.org

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-db-mysql#192] opened 2016-12-12 23:43 UTC
Relevant logs:

The queue built up to some 20,000 errors before restarting the fxa-auth-db-server fixed it all. I don't know if there was some other issue, or if it was simply the absurdly high poll rate in our stable dev environment was too much for the resources of our MySQL instance.

```
{"Timestamp":1481455936002000000,"Logger":"fxa-auth-db-server","Type":"bin.server.MySql.retryable","Severity":2,"Pid":25284,"EnvVersion":"2.0","Fields":{"err":"OperationalError: Queue limit reached."}}
{"Timestamp":1481455936002000000,"Logger":"fxa-auth-db-server","Type":"bin.server.MySql.read","Severity":2,"Pid":25284,"EnvVersion":"2.0","Fields":{"sql":"CALL fetchVerificationReminders_1(?, ?, ?, ?)","id":"[\"first\",\"20000\",\"601200000\",\"20\"]","err":"OperationalError: Queue limit reached."}}
{"Timestamp":1481455936002000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":4,"Pid":25284,"EnvVersion":"2.0","Fields":{"code":500,"route":"getverificationreminders","method":"GET","path":"/verificationReminders?reminderTime=20000&reminderTimeOutdated=601200000&type=first&limit=20","err":"Error: undefined","t":0}}
{"Timestamp":1481455936003000000,"Logger":"fxa-auth-db-server","Type":"bin.server.MySql.retryable","Severity":2,"Pid":25284,"EnvVersion":"2.0","Fields":{"err":"OperationalError: Queue limit reached."}}
{"Timestamp":1481455936003000000,"Logger":"fxa-auth-db-server","Type":"bin.server.MySql.read","Severity":2,"Pid":25284,"EnvVersion":"2.0","Fields":{"sql":"CALL fetchVerificationReminders_1(?, ?, ?, ?)","id":"[\"second\",\"40000\",\"1080000000\",\"20\"]","err":"OperationalError: Queue limit reached."}}
{"Timestamp":1481455936003000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":4,"Pid":25284,"EnvVersion":"2.0","Fields":{"code":500,"route":"getverificationreminders","method":"GET","path":"/verificationReminders?reminderTime=40000&reminderTimeOutdated=1080000000&type=second&limit=20","err":"Error: undefined","t":0}}
{"Timestamp":1481455947566000000,"Logger":"fxa-auth-db-server","Type":"bin.server.stats","Severity":6,"Pid":25284,"EnvVersion":"2.0","Fields":{"stat":"mysql","errors":11514,"connections":10,"queue":100,"free":0}}
{"Timestamp":1481455947566000000,"Logger":"fxa-auth-db-server","Type":"bin.server.mem","Severity":6,"Pid":25284,"EnvVersion":"2.0","Fields":{"rss":48189440,"heapTotal":32204896,"heapUsed":26236400}}
```

**Comment by shane-tomlinson** [comment] 2016-12-15 18:01
ref #194

**Comment by rfk** [comment] 2016-12-16 02:44
> The queue built up to some 20,000 errors 

To clarify - there were 20,000 outstanding queries in the db query queue, or there were 20,000 unhandled errors sitting around somewhere?

**Comment by seanmonstar** [comment] 2016-12-16 03:10
The log for `"Type":"bin.server.stats"` with their `"Fields":{"stat":"mysql","errors":11514,"connections":10,"queue":100,"free":0}` showed the `errors` property get up over 20,000. I was somewhere in the middle when I decided to try to copy some lines.

**Comment by jrgm** [comment] 2016-12-19 01:14
#194 is not a root cause.

This happened again on stable.dev. I restarted to fix it.

**Comment by vladikoff** [comment] 2017-01-09 21:57
Closing in favour of https://github.com/mozilla/fxa-auth-db-mysql/issues/196

**Closed by vladikoff** 2017-01-09 21:57 UTC
Labels: waffle:active
